// examples/vue/src/App.vue
<template>
  <main>
    <h1>Hello Vue!</h1>
    <button type="button" :disabled="!isWidgetReady" v-on:click="handleChangeGroup">Change group</button>
    <pre id="widget-readiness">Widget is ready: {{stringify(isWidgetReady)}}</pre>
    <pre id="widget-state">Widget state: {{stringify(widgetState)}}</pre>
    <pre id="customer-data">Customer data: {{stringify(customerData)}}</pre>
    <pre id="chat-data">Chat data: {{stringify(chatData)}}</pre>
    <pre id="greeting">Greeting: {{stringify(greeting)}}</pre>
    <LiveChatWidget
      license="12332502"
      :group="group"
      visibility="maximized"
			customerName="John Doe"
			customerEmail="john.doe@example.com"
      v-on:new-event="handleNewEvent"
      v-on:form-submitted="handleFormSubmitted"
      v-on:rating-submitted="handleRatingSubmitted"
    />
  </main>
</template>
<script lang="ts">
import { ref } from 'vue'
import {
  LiveChatWidget,
	useWidgetState,
	useWidgetIsReady,
	useWidgetChatData,
	useWidgetGreeting,
	useWidgetCustomerData,
} from '@livechat/widget-vue'

export default {
  setup() {
    const group = ref<'0' | '1'>('0')
    const chatData = useWidgetChatData()
    const greeting = useWidgetGreeting()
    const widgetState = useWidgetState()
    const isWidgetReady = useWidgetIsReady()
    const customerData = useWidgetCustomerData()

    return {
      group,
      chatData,
      greeting,
      widgetState,
      isWidgetReady,
      customerData
    }
  },
  components: {
    LiveChatWidget
  },
  methods: {
    stringify(value) {
      return JSON.stringify(value, null, 2)
    },
    handleChangeGroup() {
      this.group = this.group === '0' ? '1' : '0'
    },
    handleNewEvent(event) {
      console.log('LiveChatWidget -> onNewEvent', this.stringify(event))
    },
    handleFormSubmitted(form) {
      console.log('LiveChatWidget -> onFormSubmitted', this.stringify(form))
    },
    handleRatingSubmitted(rating) {
      console.log('LiveChatWidget -> onRatingSubmitted', this.stringify(rating))
    }
  }
}
</script>

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core'
import {
	WidgetIsReadyService,
	WidgetStateService,
	WidgetCustomerDataService,
	WidgetChatDataService,
	WidgetGreetingService,
	EventHandlerPayload,
} from '@livechat/widget-angular'

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styles: [],
})
export class AppComponent {
	group = '0'
	widgetIsReady: typeof WidgetIsReadyService.prototype.subject
	widgetState: typeof WidgetStateService.prototype.subject
	customerData: typeof WidgetCustomerDataService.prototype.subject
	chatData: typeof WidgetChatDataService.prototype.subject
	greeting: typeof WidgetGreetingService.prototype.subject

	constructor(
		widgetIsReadyService: WidgetIsReadyService,
		widgetStateService: WidgetStateService,
		widgetCustomerDataService: WidgetCustomerDataService,
		widgetChatDataService: WidgetChatDataService,
		widgetGreetingService: WidgetGreetingService,
	) {
		this.widgetIsReady = widgetIsReadyService.subject
		this.widgetState = widgetStateService.subject
		this.customerData = widgetCustomerDataService.subject
		this.chatData = widgetChatDataService.subject
		this.greeting = widgetGreetingService.subject
	}

	stringify(value: Parameters<typeof JSON.stringify>['0']) {
		return JSON.stringify(value, null, 2)
	}
	handleNewEvent(event: EventHandlerPayload<'onNewEvent'>) {
		console.log('LiveChatWidget -> onNewEvent', this.stringify(event))
	}
	handleFormSubmitted(form: EventHandlerPayload<'onFormSubmitted'>) {
		console.log('LiveChatWidget -> onFormSubmitted', this.stringify(form))
	}
	handleRatingSubmitted(rating: EventHandlerPayload<'onRatingSubmitted'>) {
		console.log('LiveChatWidget -> onRatingSubmitted', this.stringify(rating))
	}
	handleChangeGroup() {
		this.group = this.group === '0' ? '1' : '0'
	}
}

<main>
	<h1>Hello Angular!</h1>
	<button type="button" [disabled]="!(widgetIsReady$ | async)" (click)="handleChangeGroup()">Change group</button>
	<pre id="widget-readiness">Widget is ready: {{ widgetIsReady$ | async }}</pre>
	<pre id="widget-state">Widget state: {{ widgetState$ | async | json }}</pre>
	<pre id="customer-data">Customer data: {{ customerData$ | async | json }}</pre>
	<pre id="chat-data">Chat data: {{ chatData$ | async | json }}</pre>
	<pre id="greeting">Greeting: {{ greeting$ | async | json }}</pre>

	<livechat-widget
		license="12332502"
		[group]="group"
		visibility="maximized"
		customerName="John Doe"
		customerEmail="john.doe@example.com"
		(onNewEvent)="handleNewEvent($event)"
		(onFormSubmitted)="handleFormSubmitted($event)"
		(onRatingSubmitted)="handleRatingSubmitted($event)"
	></livechat-widget>
</main>
