// packages/widget-react/example/src/App.tsx
import * as React from 'react'
import {
	LiveChatWidget,
	useWidgetState,
	useWidgetIsReady,
	useWidgetChatData,
	useWidgetGreeting,
	useWidgetCustomerData,
} from '@livechat/widget-react'

function stringify(value: Parameters<typeof JSON.stringify>['0']) {
	return JSON.stringify(value, null, 2)
}

export function App() {
	const chatData = useWidgetChatData()
	const greeting = useWidgetGreeting()
	const widgetState = useWidgetState()
	const isWidgetReady = useWidgetIsReady()
	const customerData = useWidgetCustomerData()

	return (
		<main>
			<h1>Hello React!</h1>
			<pre>Widget is ready: {stringify(isWidgetReady)}</pre>
			<pre>Widget state: {stringify(widgetState)}</pre>
			<pre>Customer data: {stringify(customerData)}</pre>
			<pre>Chat data: {stringify(chatData)}</pre>
			<pre>Greeting: {stringify(greeting)}</pre>
			<LiveChatWidget
				license="12332502"
				group="0"
				visibility="maximized"
				customerName="John Doe"
				customerEmail="joh.doe@example.com"
				onNewEvent={(event) => console.log('LiveChatWidget -> onNewEvent', stringify(event))}
				onFormSubmitted={(form) => console.log('LiveChatWidget -> onFormSubmitted', stringify(form))}
				onRatingSubmitted={(rating) => console.log('LiveChatWidget -> onRatingSubmitted', stringify(rating))}
			/>
		</main>
	)
}

// packages/widget-vue/example/src/App.vue
<template>
  <main>
    <h1>Hello Vue!</h1>
    <pre>Widget is ready: {{stringify(isWidgetReady)}}</pre>
    <pre>Widget state: {{stringify(widgetState)}}</pre>
    <pre>Customer data: {{stringify(customerData)}}</pre>
    <pre>Chat data: {{stringify(chatData)}}</pre>
    <pre>Greeting: {{stringify(greeting)}}</pre>
    <LiveChatWidget
      license="12332502"
      group="0"
      visibility="maximized"
			customerName="John Doe"
			customerEmail="joh.doe@example.com"
      v-on:new-event="handleNewEvent"
      v-on:form-submitted="handleFormSubmitted"
      v-on:rating-submitted="handleRatingSubmitted"
    />
  </main>
</template>
<script lang="ts">
import {
  LiveChatWidget,
	useWidgetState,
	useWidgetIsReady,
	useWidgetChatData,
	useWidgetGreeting,
	useWidgetCustomerData,
} from '@livechat/widget-vue'

export default {
  setup() {
    const chatData = useWidgetChatData()
    const greeting = useWidgetGreeting()
    const widgetState = useWidgetState()
    const isWidgetReady = useWidgetIsReady()
    const customerData = useWidgetCustomerData()

    return {
      chatData,
      greeting,
      widgetState,
      isWidgetReady,
      customerData
    }
  },
  components: {
    LiveChatWidget
  },
  methods: {
    stringify(value) {
      return JSON.stringify(value, null, 2)
    },
    handleNewEvent(event) {
      console.log('LiveChatWidget -> onNewEvent', this.stringify(event))
    },
    handleFormSubmitted(form) {
      console.log('LiveChatWidget -> onFormSubmitted', this.stringify(form))
    },
    handleRatingSubmitted(rating) {
      console.log('LiveChatWidget -> onRatingSubmitted', this.stringify(rating))
    }
  }
}
</script>
